services:
  # Development service
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - HOST=0.0.0.0
    command: npm run dev -- --host 0.0.0.0

  # Production service
  prod:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production 